# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'PayTracker' do
    
pod 'FMDB', '2.6.2'
pod 'ObjectMapper', '1.1.5'

end

